# Generated by Django 4.1.1 on 2022-12-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_delivery'),
        ('carts', '0004_alter_cart_options_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproducts',
            options={'ordering': ['id'], 'verbose_name': 'Producto del Carrito', 'verbose_name_plural': 'Productos de los Carritos'},
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='Carrito'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el:'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
