"""
Django settings for DatStore project.
Generated by 'django-admin startproject' using Django 4.1.
For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from msilib.schema import Media
from pathlib import Path
import os
import DatStore.db as db


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATABASES = {
	'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3')
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pnd$hqgs3x2z)jvyhmwmwob#ag%rr_p_jepoar8(ftxano$ijg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGIN_URL = "/login"

ALLOWED_HOSTS = []

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

# Application definition

INSTALLED_APPS = [
    'captcha',
    'carts',
    'users',
    'orders',
    'billing_profiles',
    'promo_codes',
    'admin_interface',
    'shipping_addresses',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'categories',
    'import_export',
    'crispy_forms',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET=True

AUTHENTICATION_BACKENDS = ['allauth.account.auth_backends.AuthenticationBackend']

LOGIN_REDIRECT_URL = '/login'
LOGOUT_REDIRECT_URL = '/logout'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# only if django version >= 3.0
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DatStore.urls'

AUTH_USER_MODEL='users.User'

AUTHENTICATION_BACKENDS = ['users.backends.EmailBackend',
'allauth.account.auth_backends.AuthenticationBackend']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DatStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = db.SQLITE


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT='587'
EMAIL_USE_TLS=True
EMAIL_HOST_USER='cjmiranda135@misena.edu.co'
EMAIL_HOST_PASSWORD='Miranda110404.'

STRIPE_PUBLIC_KEY='pk_test_51M3SZqFDFKA1Kf1GzWsDrDdPD9YAMBMO1OYhdamuOExrqvfZsZfVJKNyY7TcR7kzMDb2x9o8h8O7ASDBDqd3tNT300mIMhUJYP'
STRIPE_PRIVATE_KEY='sk_test_51M3SZqFDFKA1Kf1G2BASl6Mw393x3LWZ2E6ZVX7lkDJPz1l4Y7E6lUF5RhtUzZXs5YFDV9mokMSbxyFIPR3enJWu00hdyTTcHU'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR,"static")
STATICFILES_DIRS = ["static"]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

RECAPTCHA_PUBLIC_KEY = '6LeMsdkiAAAAABqxqsZkijZVPD8PMCOZyTXs0eA6'
RECAPTCHA_PRIVATE_KEY = '6LeMsdkiAAAAAMXpuzfh3IxtSMMEsuv2L6qcbUtu'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



PASSWORD_RESET_TIMEOUT = 14400

