# Generated by Django 4.1.1 on 2022-12-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=130, null=True, verbose_name='Direccion'),
        ),
    ]
