# Generated by Django 4.1.1 on 2022-12-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['id'], 'verbose_name': 'Codigo Promocional', 'verbose_name_plural': 'Codigos Promocionales'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el:'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Valido desde'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Valido para'),
        ),
    ]
