# Generated by Django 4.1.1 on 2022-12-12 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idrolfk',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.rol', verbose_name='Identificación del Rol'),
        ),
    ]
