# Generated by Django 4.1.1 on 2023-01-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_idrolfk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
