# Generated by Django 4.1.1 on 2023-01-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Adm', 'Admin'), ('Emp', 'Employee'), ('Cli', 'Client')], default='Cliente', max_length=6, verbose_name='Rol'),
        ),
    ]
