# Generated by Django 4.1.1 on 2023-01-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
