create database DatStore
use DatStore

GO
create table ESTADO	
(
    ID_ESTADO int identity PRIMARY KEY NOT NULL,
	NOMBRE_ESTADO VARCHAR (20) not null,
)
GO

GO
create table PROVEEDOR	
(
    ID_PROV int IDENTITY PRIMARY KEY NOT NULL,
	NOMBRE_PROV VARCHAR (20) not null,
	TEL_PROV BIGINT not null,
	CORREO_PROV VARCHAR (50) not null,
	DIREC_PROV VARCHAR (50) NOT NULL,
	ID_ESTADO_FK_PROV INT,
	FOREIGN KEY (ID_ESTADO_FK_PROV) REFERENCES ESTADO(ID_ESTADO)
)
GO

GO
CREATE TABLE TIPO_PROD
(
	ID_TIP_PROD INT IDENTITY PRIMARY KEY NOT NULL,
	NOMBRE_TIP_PROD VARCHAR (20) NOT NULL,
	ID_ESTADO_FK_TIP_PROD INT,
	FOREIGN KEY (ID_ESTADO_FK_TIP_PROD) REFERENCES ESTADO(ID_ESTADO)
)
GO

GO
CREATE TABLE ROL
(
	ID_ROL INT IDENTITY PRIMARY KEY NOT NULL,
	NOMBRE_ROL VARCHAR (20) NOT NULL,
)
GO

GO
create TABLE FORMA_PAGO
(
	ID_F_PAG INT IDENTITY PRIMARY KEY NOT NULL,
	NOMBRE_F_PAG VARCHAR(20) NOT NULL,
	ID_ESTADO_FK_F_PAG INT NOT NULL
)
GO

GO
create TABLE USUARIO
(
	ID_USUARIO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE_USUARIO VARCHAR (40) NOT NULL,
	CONTRASENA VARCHAR (40) NOT NULL,
	DIRECCION_USUARIO VARCHAR (80) NOT NULL,
	CORREO_USUARIO VARCHAR (50) NOT NULL,
	TEL_USUARIO BIGINT NOT NULL,
	ID_ESTADO_FK_USUARIO INT NOT NULL,
	FOREIGN KEY (ID_ESTADO_FK_USUARIO) REFERENCES ESTADO(ID_ESTADO),
	ID_ROL_FK_USUARIO INT NOT NULL,
	FOREIGN KEY (ID_ROL_FK_USUARIO) REFERENCES ROL(ID_ROL)
)
GO
GO
CREATE TABLE PRODUCTO 
(
	ID_PROD INT IDENTITY PRIMARY KEY NOT NULL,
	NOMBRE_PROD VARCHAR (80) NOT NULL,
	ID_TIPO_PROD_FK_PROD INT,
	FOREIGN KEY (ID_TIPO_PROD_FK_PROD) REFERENCES TIPO_PROD(ID_TIP_PROD),
	ID_PROV_FK_PROD INT,
	FOREIGN KEY (ID_PROV_FK_PROD) REFERENCES PROVEEDOR(ID_PROV),
	ID_ESTADO_FK_PROD INT,
	FOREIGN KEY (ID_ESTADO_FK_PROD) REFERENCES ESTADO(ID_ESTADO)
)
GO

GO
CREATE TABLE INVENTARIO
(
	ID_INV INT PRIMARY KEY NOT NULL,
	CANT_ACT_INV INT NOT NULL,
	ID_PROD_FK_INV INT NOT NULL
	FOREIGN KEY (ID_PROD_FK_INV) REFERENCES PRODUCTO(ID_PROD)
)
GO

GO
CREATE TABLE ENT_INVENTARIO
(
	ID_ENT_INV BIGINT IDENTITY PRIMARY KEY NOT NULL,
	CANT_ENT_INV BIGINT NOT NULL,
	FECHA_ENT_INV DATETIME NOT NULL,
	ID_PROD_FK_ENT_INV INT NOT NULL,
	FOREIGN KEY (ID_PROD_FK_ENT_INV) REFERENCES PRODUCTO(ID_PROD),
	PRECIO_C_ENT_INV BIGINT NOT NULL,
	COSTE_GRUP_PROD_ENT_INV BIGINT NOT NULL,
	ID_EST_FK_ENTINV INT,
	FOREIGN KEY (ID_EST_FK_ENTINV) REFERENCES ESTADO(ID_ESTADO),
	ID_USU_FK_ENTINV BIGINT, 
	FOREIGN KEY (ID_USU_FK_ENTINV) REFERENCES USUARIO(ID_USUARIO)
)
GO

GO
CREATE TABLE SAL_INVENTARIO
(
	ID_SAL_INV BIGINT IDENTITY PRIMARY KEY NOT NULL,
	CANT_SAL_INV BIGINT NOT NULL,
	FECHA_SAL_INV DATETIME NOT NULL,
	ID_PROD_FK_SAL_INV INT NOT NULL,
	FOREIGN KEY (ID_PROD_FK_SAL_INV) REFERENCES PRODUCTO(ID_PROD),
	PRECIO_V_SAL_INV BIGINT NOT NULL,
	COSTE_GRUP_PROD_SAL_INV BIGINT NOT NULL,
	ID_EST_FK_SALINV INT,
	FOREIGN KEY (ID_EST_FK_SALINV) REFERENCES ESTADO(ID_ESTADO),
	ID_USU_FK_SALINV BIGINT, 
	FOREIGN KEY (ID_USU_FK_SALINV) REFERENCES USUARIO(ID_USUARIO)
)
GO

GO
CREATE TABLE PEDIDO
(
	ID_PEDIDO BIGINT IDENTITY PRIMARY KEY NOT NULL,
	FECHA_PED DATETIME NOT NULL,
	TIP_ENTREGA VARCHAR (15) NOT NULL,
	TOTAL_PEDIDO BIGINT NOT NULL,
	ID_USUARIO_FK_PED BIGINT NOT NULL,
	FOREIGN KEY (ID_USUARIO_FK_PED) REFERENCES USUARIO(ID_USUARIO),
	ID_F_PAG_FK_PED INT NOT NULL,
	FOREIGN KEY (ID_F_PAG_FK_PED) REFERENCES FORMA_PAGO(ID_F_PAG),
	ID_ESTADO_FK_PED INT NOT NULL,
	FOREIGN KEY (ID_ESTADO_FK_PED) REFERENCES ESTADO(ID_ESTADO),
)
GO

GO
CREATE TABLE DET_PED_INV
(
	ID_DET_PED BIGINT IDENTITY PRIMARY KEY NOT NULL,
	ID_SAL_INV_FK_DET BIGINT NOT NULL,
	FOREIGN KEY (ID_SAL_INV_FK_DET) REFERENCES SAL_INVENTARIO(ID_SAL_INV),
	ID_PEDIDO_FK_DET BIGINT NOT NULL,
	FOREIGN KEY (ID_PEDIDO_FK_DET) REFERENCES PEDIDO(ID_PEDIDO),
)
GO

GO
CREATE TABLE DOMICILIO
(
	ID_DOMICILIO BIGINT IDENTITY PRIMARY KEY NOT NULL,
	ID_PED_FK_DOM BIGINT NOT NULL,
	FOREIGN KEY (ID_PED_FK_DOM) REFERENCES PEDIDO(ID_PEDIDO),
	ID_ESTADO_FK_DOM INT NOT NULL,
	FOREIGN KEY (ID_ESTADO_FK_DOM) REFERENCES ESTADO(ID_ESTADO),
	DIREC_USUARIO VARCHAR (80),
	FECHA_DOMICILIO DATE
)
GO

SELECT *FROM DET_PED_INV
SELECT *FROM DOMICILIO
SELECT *FROM PEDIDO
SELECT *FROM ENT_INVENTARIO
SELECT *FROM ESTADO
SELECT *FROM FORMA_PAGO
SELECT *FROM INVENTARIO
SELECT *FROM PRODUCTO
SELECT *FROM TIPO_PROD
SELECT *FROM PROVEEDOR
SELECT *FROM ROL
SELECT *FROM SAL_INVENTARIO
SELECT *FROM USUARIO

