Use DatStore

---Mostrar las ventas realizadas para un Cliente donde se puede ver que rol que posee 
--,el nombre del producto que compro , la cantidad que llevo y el precio del conjunto de productos que llevo
go
SELECT ID_USUARIO AS CEDULA,NOMBRE_USUARIO AS NOMBRE,NOMBRE_ROL,ID_PROD,NOMBRE_PROD AS PRODUCTO,PRECIO_V_SAL_INV AS PRECIO_VENTA,
CANT_SAL_INV AS CANTIDAD,COSTE_GRUP_PROD_SAL_INV AS TOTAL 
FROM ROL
inner join USUARIO on ROL.ID_ROL = ID_ROL_FK_USUARIO
inner join SAL_INVENTARIO on USUARIO.ID_USUARIO = ID_USU_FK_SALINV
inner join PRODUCTO on SAL_INVENTARIO.ID_PROD_FK_SAL_INV = ID_PROD
WHERE ID_ROL = '3' AND COSTE_GRUP_PROD_SAL_INV between '0' and '10000000' 
GROUP BY ID_USUARIO,NOMBRE_USUARIO,NOMBRE_ROL,ID_PROD,NOMBRE_PROD,PRECIO_V_SAL_INV,CANT_SAL_INV,COSTE_GRUP_PROD_SAL_INV
having CANT_SAL_INV > ''
go

SELECT * FROM VENTAS

---Consulta donde solo los administradores consultar las compras durante un periodo de un año (2020), filtrado por un proveedor
go
select ID_USUARIO AS CEDULA,NOMBRE_USUARIO AS NOMBRE,ID_PROD,NOMBRE_PROD AS PRODUCTO, 
NOMBRE_PROV AS PROVEDOR,FECHA_ENT_INV AS FECHA_COMPRA,CANT_ENT_INV,PRECIO_C_ENT_INV, 
COSTE_GRUP_PROD_ENT_INV,
SUM(CANT_ENT_INV*PRECIO_C_ENT_INV) as TOTAL from USUARIO
inner join ENT_INVENTARIO on USUARIO.ID_USUARIO=ID_USU_FK_ENTINV
inner join PRODUCTO on ENT_INVENTARIO.ID_PROD_FK_ENT_INV=ID_PROD
inner join PROVEEDOR on PRODUCTO.ID_PROV_FK_PROD=ID_PROV
WHERE FECHA_ENT_INV between '01/01/2021' and '31/12/2021' AND CANT_ENT_INV>= ALL (SELECT AVG (CANT_ENT_INV) FROM ENT_INVENTARIO)
group by ID_USUARIO,NOMBRE_USUARIO,ID_PROD,NOMBRE_PROD, NOMBRE_PROV,CANT_ENT_INV,PRECIO_C_ENT_INV,FECHA_ENT_INV, 
COSTE_GRUP_PROD_ENT_INV
go

-----Consulta todos los datos de un pedido y los productos que se compraron es este
go
declare @idpd bigint
set @idpd=8
select ID_USUARIO AS CEDULA,NOMBRE_USUARIO AS NOMBRE,ID_PEDIDO,FECHA_PED AS FECHA_PEDIDO,TIP_ENTREGA,
ID_DOMICILIO,DIREC_USUARIO,TOTAL_PEDIDO,NOMBRE_ESTADO from USUARIO
inner join PEDIDO on USUARIO.ID_USUARIO=PEDIDO.ID_USUARIO_FK_PED
inner join DOMICILIO on PEDIDO.ID_PEDIDO=DOMICILIO.ID_PED_FK_DOM
inner join ESTADO on ESTADO.ID_ESTADO=DOMICILIO.ID_ESTADO_FK_DOM
where ID_PEDIDO=@idpd
(select ID_PROD,NOMBRE_PROD,ID_SAL_INV AS PRODUCTO,CANT_SAL_INV,PRECIO_V_SAL_INV,SUM(CANT_SAL_INV*PRECIO_V_SAL_INV)
as TOTAL from PEDIDO
inner join DET_PED_INV on PEDIDO.ID_PEDIDO=DET_PED_INV.ID_PEDIDO_FK_DET
inner join SAL_INVENTARIO on SAL_INVENTARIO.ID_SAL_INV=DET_PED_INV.ID_SAL_INV_FK_DET
inner join PRODUCTO on SAL_INVENTARIO.ID_PROD_FK_SAL_INV=ID_PROD 
where ID_PEDIDO_FK_DET=@idpd
group by ID_PROD,NOMBRE_PROD,ID_SAL_INV,CANT_SAL_INV,PRECIO_V_SAL_INV)
go

--Mostrar los domicilios entregados en el año 2020 y los productos de un pedido en especifico
go
declare @dom bigint
set @dom=52846103
Select ID_DOMICILIO,ID_USUARIO AS CEDULA,NOMBRE_USUARIO AS NOMBRE,DIREC_USUARIO,FECHA_DOMICILIO,NOMBRE_ESTADO
From USUARIO
inner join PEDIDO on USUARIO.ID_USUARIO=PEDIDO.ID_USUARIO_FK_PED
inner join DOMICILIO on ID_PED_FK_DOM=ID_PEDIDO
inner join ESTADO on ESTADO.ID_ESTADO=DOMICILIO.ID_ESTADO_FK_DOM
where FECHA_DOMICILIO between '01/01/2020' and '31/12/2020' AND NOMBRE_ESTADO='Inactivo'
(select ID_PROD,NOMBRE_PROD AS PRODUCTO,CANT_SAL_INV,PRECIO_V_SAL_INV,SUM(CANT_SAL_INV*PRECIO_V_SAL_INV) as TOTAL from PEDIDO
inner join DET_PED_INV on PEDIDO.ID_PEDIDO=DET_PED_INV.ID_PEDIDO_FK_DET
inner join SAL_INVENTARIO on SAL_INVENTARIO.ID_SAL_INV=DET_PED_INV.ID_SAL_INV_FK_DET
inner join PRODUCTO on SAL_INVENTARIO.ID_PROD_FK_SAL_INV=ID_PROD
WHERE ID_USUARIO_FK_PED=52846103
group by ID_PROD,NOMBRE_PROD,ID_SAL_INV,CANT_SAL_INV,PRECIO_V_SAL_INV)
go
