# Generated by Django 4.1.1 on 2022-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Precio del domicilio'),
        ),
        migrations.AlterField(
            model_name='detorder',
            name='costgp',
            field=models.PositiveIntegerField(verbose_name='Precio grupo producto'),
        ),
        migrations.AlterField(
            model_name='detorder',
            name='quant',
            field=models.PositiveIntegerField(verbose_name='Cantidad productos'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='groupcost',
            field=models.PositiveIntegerField(verbose_name='Coste del grupo de productos'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='purchaseprice',
            field=models.PositiveIntegerField(verbose_name='Precio de compra de los productos'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad de la entradad'),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='totalpurchase',
            field=models.PositiveIntegerField(verbose_name='Total Compra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total del pedido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costp',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Precio producto indiv.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Id del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Cantidad del producto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Id del proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Número de telefono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.PositiveIntegerField(verbose_name='Numero del Celular'),
        ),
    ]
