# Generated by Django 4.1 on 2022-09-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statord',
            field=models.CharField(choices=[('Ent', 'Entregado'), ('Pen', 'Pendiente')], max_length=4, verbose_name='Estado Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='typedel',
            field=models.CharField(choices=[('Dom', 'Domicilio'), ('Tie', 'Tienda')], max_length=4, verbose_name='Tipo Entrega'),
        ),
    ]
