# Generated by Django 4.1 on 2022-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_statord_alter_order_typedel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='idprodFK',
            field=models.ManyToManyField(to='core.rol', verbose_name='Rol'),
        ),
    ]
