# Generated by Django 4.1 on 2022-11-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_delivery_price_alter_detorder_costgp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='totalpurchase',
            field=models.PositiveBigIntegerField(verbose_name='Total Compra'),
        ),
        migrations.AlterField(
            model_name='inventoryoutput',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Cantidad de la Salida'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Nombre del permiso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveBigIntegerField(verbose_name='Cantidad del producto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email del proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id del proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Nombre del proveedor'),
        ),
        migrations.AlterField(
            model_name='users',
            name='condition',
            field=models.TextField(max_length=15, verbose_name='Estado del Usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Correo del Usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id del Usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastn',
            field=models.TextField(max_length=20, verbose_name='Primer apellido del Usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastns',
            field=models.TextField(max_length=20, verbose_name='Segundo apellido del Usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(max_length=20, verbose_name='Primer nombre del Usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='names',
            field=models.TextField(max_length=20, verbose_name='Segundo nombre del Usuario'),
        ),
        migrations.AlterField(
            model_name='waytopay',
            name='name',
            field=models.TextField(max_length=15, verbose_name='Nombre de la forma de pago'),
        ),
    ]
