# Generated by Django 4.1.1 on 2022-11-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_inventoryentry_totalpurchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='refpayment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Referencia de pago'),
        ),
    ]
