# Generated by Django 4.1.1 on 2022-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_inventoryentry_refpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=30, verbose_name='Nombre del producto'),
        ),
    ]
