# Generated by Django 4.1.1 on 2022-12-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
