# Generated by Django 4.1.1 on 2022-12-11 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_inventoryentry_totalpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Identificación del Usuario'),
        ),
    ]
