# Generated by Django 4.1.1 on 2022-12-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_entrydetail_groupcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='totalpurchase',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Total Compra'),
        ),
    ]
